# Directories
dir:
  node  : ./node_modules/
  src   : ./src/
  vendor: ./vendor/

# gulp-sass
# @link https://www.npmjs.com/package/gulp-sass
# @link https://github.com/sass/node-sass
sass:
  development:
    includePaths: &includePaths
      - ./_sass
  production:
    includePaths: *includePaths
    outputStyle : compressed

# gulp-uglify
# @link https://www.npmjs.com/package/gulp-uglify
# @link https://github.com/mishoo/UglifyJS
uglify:
  mangle          : true
  preserveComments: license
